# Python pip installs working check.
python-job-install-requirements:
    image: python:3.6
    script:
        - pip install -r src/requirements.txt

# Python tests working check.
py36_nose:
    image: python:3.6
    script:
        - pip install -r src/requirements.txt
        - nosetests --verbosity=3 --nocapture -w src/